apiVersion: apps.zhh960713.xyz/v1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: application
    app.kubernetes.io/instance: application-sample
    app.kubernetes.io/part-of: kubebuilder-demo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubebuilder-demo
  name: application-sample
spec:
  # TODO(user): Add fields here
